# -*- coding: utf-8 -*-
"""Atividade ADS - IESB.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gcwbGXEeHTOZMglVx38D30qc4fOVWu9V

#Menu do programa
"""

print("Bem vindo ao menu principal!")
tfMenu = True
while tfMenu == True:
  opcao = input("\
  1 - Inserir novo contato\
  \n\
  2 - Consultar contato\
  \n\
  3 - Alterar contato\
  \n\
  4 - Remover contato\
  \n\
  X - Sair da aplicação\
  \n")
  if(opcao.upper() == "X"):
    print("Você fechou a aplicação")
    tfMenu = False
  elif(opcao.upper() == "1"):
    print("Inserir")
  elif(opcao.upper() == "2"):
    print("Consultar")
  elif(opcao.upper() == "3"):
    print("Alterar")
  elif(opcao.upper() == "4"):
    print("Remover")

"""#Inserir contato"""





