# -*- coding: utf-8 -*-
"""Atividade ADS - IESB.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gcwbGXEeHTOZMglVx38D30qc4fOVWu9V

#Funções
"""

#Adicionar um novo usuario dentro do dicionario
def InserirContato(nome, telefone, email, twitter, instagram):
  listaContatos[nome] = {"telefone": telefone, "email":email, "twitter":twitter, "instagram": instagram}
  print("================Usuario "+nome+" Cadastrado com sucesso================")

#Consulta dados do contato referente ao nome fornecido
def ConsultarContato(nome):
  if(nome in listaContatos):
    print(\
        "=================Nome:"+nome+", Email:"+listaContatos[nome]["email"]+", Twitter:"+listaContatos[nome]["twitter"] +", Instagram:"+listaContatos[nome]["instagram"]+"=================")
  else:
    print("========X========Esse contato não existe========X========")

#Deleta todos os dados do contato referente ao nome fornecido
def RemoverContato(nome):
  if(nome in listaContatos):
   listaContatos.pop(nome)
   print("=================Contato "+nome+" deletado com sucesso=================")
  else:
    print("========X========Esse contato não existe========X========")

#Relatorio de contatos
def GerarRelatorio():
  print("Nome \t|\t E-mail \t|\t Twitter \t|\t Instagram")
  for i in listaContatos.keys():
    #print values
    print("{0}    \t|\t {1}     \t|\t {2}       \t|\t {3}".format(i,listaContatos[i]["email"], listaContatos[i]["twitter"], listaContatos[i]["instagram"]) )

"""#Menu do programa

"""

listaContatos = {}
print("Bem vindo ao menu principal!")
tfMenu = True
while tfMenu == True:  
  print("==============================================")
  print("==============================================")
  opcao = input("\
  1 - Inserir novo contato\
  \n\
  2 - Consultar contato\
  \n\
  3 - Alterar contato\
  \n\
  4 - Remover contato\
  \n\
  5 - Gerar relatorio\
  \n\
  X - Sair da aplicação\
  \n")
  if(opcao.upper() == "X"):
    print("Você fechou a aplicação")
    tfMenu = False
  elif(opcao.upper() == "1"):
    x= 0 
    countNewContact = int(input("Digite quantos contatos serão adicionados"))
    while x < countNewContact:      
      InserirContato(input("Nome:"), input("Telefone:"), input("Email"), input("Twitter"), input("Instagram"))
      x = x+1
  elif(opcao.upper() == "2"):
    ConsultarContato(input("Digite um nome para consultar: "))
  #elif(opcao.upper() == "3"):
    #AlterarContato(input("Digite um nome do contato para alteração: "))
  elif(opcao.upper() == "4"):
    RemoverContato(input("Digite o nome do contato que será deletado: "))
  elif(opcao.upper() == "5"):
    GerarRelatorio()