# -*- coding: utf-8 -*-
"""Atividade ADS - IESB.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gcwbGXEeHTOZMglVx38D30qc4fOVWu9V

#Inserir contato
"""

def InserirContato(nome, telefone, email, twitter, instagram):
  listaContatos["nome"] = {"telefone": telefone, "email":email, "twitter":twitter, "instagram": instagram}

"""#Menu do programa

"""

listaContatos = {}
print("Bem vindo ao menu principal!")
tfMenu = True
while tfMenu == True:
  opcao = input("\
  1 - Inserir novo contato\
  \n\
  2 - Consultar contato\
  \n\
  3 - Alterar contato\
  \n\
  4 - Remover contato\
  \n\
  X - Sair da aplicação\
  \n")
  if(opcao.upper() == "X"):
    print("Você fechou a aplicação")
    tfMenu = False
  elif(opcao.upper() == "1"):
    InserirContato(input("Nome:"), input("Telefone:"), input("Email"), input("Twitter"), input("instagram"))
  elif(opcao.upper() == "2"):
    print("Consultar")
  elif(opcao.upper() == "3"):
    print("Alterar")
  elif(opcao.upper() == "4"):
    print("Remover")



